# Generated by Django 4.2.11 on 2024-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusobites', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='method_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
